### ISSUE TITLE
A left sidebar has it's drop shadow on the wrong side

### ISSUE THREAD

**Issue by NeilBrommer** [wsuwebteam/web-design-system#35]
A sidebar on the right puts the drop shadow on the inside edge (between the columns):

![image](https://github.com/wsuwebteam/web-design-system/assets/9068365/891b4920-6167-4f2d-8496-24d3dfa0ed8c)

However a left sidebar puts the drop shadow on the outside edge ([CodePen example](https://codepen.io/NeilBrommer/pen/NWJNPEM?editors=1000)):

![image](https://github.com/wsuwebteam/web-design-system/assets/9068365/1263a88c-d6b5-4084-8da8-bc8b58d07a7a)

This is the SCSS I'm using to fix this ([CodePen example](https://codepen.io/NeilBrommer/pen/MWxyYZL?editors=1100)):

```scss
.wsu-row--sidebar-left {
	.wsu-column--style-sidebar {
		border-left: none;
		border-right: 1px solid #e5e5e5;

		&::before {
			display: none;
		}

		&::after {
			content: "";
			position: absolute;
			display: block;
			top: 0;
			bottom: 0;
			right: -30px;
			width: 30px;
			height: auto;
			background: linear-gradient(
				to left,
				rgba(0, 0, 0, 0) 0,
				rgba(0, 0, 0, 0.05) 100%
			);
		}
	}
}
```

And this is what the result looks like:

![image](https://github.com/wsuwebteam/web-design-system/assets/9068365/c98766a8-a9b9-4ee1-be94-1b91817e218a)
