### ISSUE TITLE
Accordion titles have button styling when in `.wsu-content`

### ISSUE THREAD

**Issue by NeilBrommer** [wsuwebteam/web-design-system#36]
Example ([CodePen](https://codepen.io/NeilBrommer/pen/wvOogqY?editors=1000)):

![image](https://github.com/wsuwebteam/web-design-system/assets/9068365/bb584fcb-9af8-42b3-bc24-566f2196f7ea)

I'm using this SCSS to restore the accordion styling ([CodePen](https://codepen.io/NeilBrommer/pen/GReNrMd?editors=1100)):

```scss
.wsu-accordion .wsu-accordion__title .wsu-accordion__title-button {
    color: inherit;
    font-size: 1.5rem;
    line-height: 1.3;
    font-weight: 400;
    background-color: transparent;
    margin-bottom: 0;

    &:hover,
    &:focus {
        background-color: transparent;
        box-shadow: none;
    }
}
```
