### ISSUE TITLE
Make check boxes and radio buttons crimson

### ISSUE THREAD

**Issue by NeilBrommer** [wsuwebteam/web-design-system#45]
Check boxes and radio buttons currently just use the browser's default color (usually blue):
![image](https://github.com/wsuwebteam/web-design-system/assets/9068365/93b0c5fa-2355-46b5-9534-3bf00abbfe02)

It's easy to set the color of these by setting an `accent-color` (I've also made them larger in this example):
![image](https://github.com/wsuwebteam/web-design-system/assets/9068365/483eecd6-df6e-4fd0-838f-803906b3f78c)

The CSS:

```scss
input[type="checkbox"],
input[type="radio"] {
	accent-color: #ca1237;
	transform: scale(2) translateX(50%);
	margin-right: 0.5rem;
}
```
